// Code generated by Prismic. DO NOT EDIT.

import AfterTypeBuilder from "./AfterTypeBuilder";
import DemoOne from "./DemoOne";
import DemoTwo from "./DemoTwo";

export const components = {
	after_type_builder: AfterTypeBuilder,
	demo_one: DemoOne,
	demo_two: DemoTwo
};